// examples/tikua-front-vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Tikua, Address } from '@doiim/tikua'

import VueJsonPretty from 'vue-json-pretty'
import 'vue-json-pretty/lib/styles.css';

// Add property to allow JSON to be serialized on the frontend
// @ts-ignore
BigInt.prototype.toJSON = function () { return this.toString() }

const ABI = [
  "struct Dragon { uint256 id; uint256 life; }",
  "function attackDragon(uint256 dragonId)",
  "function drinkPotion()",
  "function heroStatus(address player) returns (uint256)",
  "function dragonStatus(uint256 dragonId) returns (uint256)",
  "function dragonsList() returns (Dragon[])",
];

const walletAddress = ref<Address>();
const provider = ref()
const dragonIdInput = ref('')
const message = ref<any>({})
const isDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;

const connect = async () => {
  if (!window.ethereum) throw Error('MetaMask not found')
  await window.ethereum.request({ method: 'wallet_addEthereumChain', params: [{ chainId: '0x7A69', chainName: "Local Anvil", nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 }, rpcUrls: ['http://localhost:8545'] }] });
  const [account] = await window.ethereum.request({ method: 'eth_requestAccounts' })
  if (!account) throw Error('MetaMask reject')
  walletAddress.value = account
  provider.value = window.ethereum
  await startSubscription()
}

const startSubscription = async () => {
  if (!provider.value || !walletAddress.value) throw Error('Wallet not connected')
  const tikua = new Tikua({
    provider: provider.value,
    endpoint: 'http://localhost:8080',
    abi: ABI
  })
  tikua.addMyNoticesListener(
    1000,
    walletAddress.value,
    (e) => message.value = e
  )
}

const drinkPotion = async () => {
  if (!walletAddress.value) return
  const tikua = new Tikua({
    provider: provider.value,
    address: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
    account: walletAddress.value,
    abi: ABI
  })
  await tikua.sendInput('drinkPotion', [])
}

const checkLife = async () => {
  if (!walletAddress.value) return
  const tikua = new Tikua({
    provider: provider.value,
    endpoint: 'http://localhost:8080',
    abi: ABI
  })
  const status = await tikua.fetchInspect('heroStatus', [walletAddress.value])
  message.value = {
    life: status
  }
}

const dragonsList = async () => {
  const tikua = new Tikua({
    provider: provider.value,
    endpoint: 'http://localhost:8080',
    address: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
    abi: ABI
  })
  const status = await tikua.fetchInspect('dragonsList', []) as any[]
  message.value = status
}

const checkDragon = async () => {
  if (!dragonIdInput.value) return
  const tikua = new Tikua({
    provider: provider.value,
    endpoint: 'http://localhost:8080',
    address: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
    abi: ABI
  })
  const status = await tikua.fetchInspect('dragonStatus', [dragonIdInput.value])
  message.value = {
    drago: dragonIdInput.value,
    status: status
  }
}

const attackDragon = async () => {
  if (!dragonIdInput.value) return
  const tikua = new Tikua({
    provider: provider.value,
    address: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
    account: walletAddress.value,
    abi: ABI
  })
  await tikua.sendInput('attackDragon', [dragonIdInput.value])
}

</script>

<template>
  <div class="text-stone-600 dark:text-stone-300  overflow-hidden">
    <img src="./assets/logo.png" width=200 height=200 class="mx-auto" />
    <div class="text-center">
      <h1 class="text-5xl font-semibold">Tikua</h1>
      <p>an isomorphic Cartesi SDK</p>
    </div>


    <div class="my-10 text-center">
      <button v-if="!walletAddress" @click="connect"
        class="bg-stone-100 dark:bg-stone-800 rounded-lg p-2 px-4 font-semibold text-lg hover:outline hover:outline-1 hover:outline-blue-600">Connect
        Wallet</button>
      <p v-else>Wallet: <span class="text-orange-400">{{ walletAddress }}</span></p>
    </div>

    <p class="my-2 text-center">
      After connect your wallet successfully. Fill the form above.
    </p>

    <div
      class="bg-stone-50 dark:bg-stone-700 rounded-lg p-4 flex flex-col gap-2 border border-stone-100 dark:border-stone-800 w-[600px] my-2">
      <h1 class="uppercase text-sm font-semibold text-stone-500 dark:text-stone-300">Hero</h1>
      <div class="flex gap-4">
        <button :disabled="!walletAddress" @click="checkLife"
          class="bg-stone-100 dark:bg-stone-800 rounded-lg p-2 px-4  text-md hover:outline hover:outline-1 hover:outline-blue-600">Check
          Health</button>
        <button :disabled="!walletAddress" @click="drinkPotion"
          class="bg-stone-100 dark:bg-stone-800 rounded-lg p-2 px-4  text-md hover:outline hover:outline-1 hover:outline-blue-600">Drink
          Potion</button>
      </div>
    </div>


    <form
      class="bg-stone-50 dark:bg-stone-700 rounded-lg p-4 flex flex-col gap-2 border border-stone-100 dark:border-stone-800 w-[600px] my-2">
      <h1 class="uppercase text-sm font-semibold text-stone-500 dark:text-stone-300">Dragon</h1>
      <div>
        <button @click.prevent="dragonsList"
          class="bg-stone-100 dark:bg-stone-800 rounded-lg p-2 px-4  text-md hover:outline hover:outline-1 hover:outline-blue-600">List
          All Dragons</button>
      </div>
      <div class="flex gap-4">
        <input v-model="dragonIdInput" placeholder="Enter a dragon ID"
          class="bg-white dark:bg-stone-800 rounded-lg p-2 px-4  text-md focus:outline focus:outline-1 focus:outline-blue-600 w-40" />

        <button @click.prevent="checkDragon" v-if="dragonIdInput"
          class="bg-stone-100 dark:bg-stone-800 rounded-lg p-2 px-4  text-md hover:outline hover:outline-1 hover:outline-blue-600">Check
          Health</button>
        <button @click.prevent="attackDragon" :disabled="!walletAddress" v-if="dragonIdInput"
          class="bg-stone-100 dark:bg-stone-800 rounded-lg p-2 px-4  text-md hover:outline hover:outline-1 hover:outline-blue-600">Attack</button>
      </div>
    </form>

    <VueJsonPretty :data="message" :show-icon="true" :theme="isDarkMode ? 'dark' : 'light'"
      class="bg-stone-50 dark:bg-stone-700 rounded-lg p-4" />

  </div>
</template>

// examples/tikua-front-react/src/App.tsx
import { useEffect, useState } from 'react'
import './App.css'
import { Tikua, Address } from '@doiim/tikua'
import ReactJson from '@vahagn13/react-json-view'
import logo from './assets/logo.png'

// Add property to allow JSON to be serialized on the frontend
// @ts-ignore
BigInt.prototype.toJSON = function () { return this.toString() }

// Defining Dapp ABI
const abi = [
  "struct Dragon { uint256 id; uint256 life; }",
  "function attackDragon(uint256 dragonId)",
  "function drinkPotion()",
  "function heroStatus(address player) returns (uint256)",
  "function dragonStatus(uint256 dragonId) returns (uint256)",
  "function dragonsList() returns (Dragon[])",
];

function App() {

  const [wallet, setWallet] = useState<Address>()
  const [provider, setProvider] = useState<any>()
  const [dragonId, setDragonId] = useState<number>(0)
  const [message, setMessage] = useState<object>({})
  const [isDarkMode, setIsDarkMode] = useState<boolean>(false)

  useEffect(() => {
    // Add listener to update styles
    window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', e => setIsDarkMode(e.matches ? true : false));

    // Setup dark/light mode for the first time
    setIsDarkMode(window.matchMedia('(prefers-color-scheme: dark)').matches ? true : false)

    // Remove listener
    return () => {
      // unsubscribe()
      window.matchMedia('(prefers-color-scheme: dark)').removeEventListener('change', () => { })
    }
    connectWallet()
  }, [])

  const connectWallet = async () => {
    if (!window.ethereum) throw Error("MetaMask not found");
    await window.ethereum.request({
      method: "wallet_addEthereumChain",
      params: [
        {
          chainId: "0x7A69",
          chainName: "Local Anvil",
          nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
          rpcUrls: ["http://localhost:8545"],
        },
      ],
    });
    const [account] = await window.ethereum.request({
      method: "eth_requestAccounts",
    });
    if (!account) throw Error("MetaMask reject");

    setWallet(account);
    setProvider(window.ethereum);

    await startSubscription(account);
  }

  const attackDragon = async (e: any) => {
    e.preventDefault()
    const tikua = new Tikua({
      provider,
      appAddress: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
      signerAddress: wallet,
      abi
    })
    await tikua.sendInput('attackDragon', [dragonId])
  }

  const drinkPotion = async () => {
    const tikua = new Tikua({
      provider: provider,
      appAddress: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
      signerAddress: wallet,
      abi
    })
    await tikua.sendInput('drinkPotion', [])
  }

  const checkLife = async () => {
    const tikua = new Tikua({
      appEndpoint: 'http://localhost:8080',
      abi
    })
    const status = await tikua.fetchInspect('heroStatus', [wallet])
    setMessage({
      life: status
    })
  }

  const checkDragon = async (e: any) => {
    e.preventDefault()
    const tikua = new Tikua({
      appEndpoint: 'http://localhost:8080',
      abi: abi
    })
    const status = await tikua.fetchInspect('dragonStatus', [dragonId])
    setMessage({
      dragonId: dragonId,
      status: status
    });
  }

  const dragonsList = async (e: any) => {
    e.preventDefault()
    const tikua = new Tikua({
      appEndpoint: 'http://localhost:8080',
      abi: abi
    })
    const status = await tikua.fetchInspect('dragonsList', []) as any[]
    setMessage(status);
  }

  /**
   * This function starts a subscription by creating a new CartesiSDK instance
   * and adding a notices listener that updates the message state.
   *
   * @return {Promise<void>} Returns a Promise that resolves when the notices listener is added.
   */
  const startSubscription = async (account: Address) => {
    const tikua = new Tikua({
      appEndpoint: 'http://localhost:8080',
      abi: abi
    })
    return tikua.addMyNoticesListener(
      1000,
      account,
      (e) => setMessage(e)
    )
  }

  return (
    <>
      <img src={logo} width={200} height={200}></img>
      <h1>Tikua</h1>
      <p>an isomorphic Cartesi SDK</p>
      <div className="card">
        {!wallet ?
          <button onClick={connectWallet}>Connect Wallet</button>
          : <p>Wallet: <span className='orange'>{wallet}</span></p>}
        {wallet ? <>
          <div className='heroCommands'>
            <div>
              <button onClick={drinkPotion}>Drink Potion</button>
              <p>
                <strong>Drink Potion:</strong> This is a write request that sends an
                input to the dApp, triggering the advance execution, which will
                generate notices.
              </p>
            </div>
            <div>
              <button onClick={checkLife}>Check Hero Status</button>
              <p>
                <strong>Check Health:</strong> This is a read-only request that sends
                an inspect request to the dApp and retrieves a report on the health
                status.
              </p>
            </div>
          </div>
          <div className='dragonCommands'>
            <button onClick={dragonsList}>List Dragons</button>
            <p>
              <strong>List All Dragons and Check Health:</strong> This is a
              read-only request that sends an inspect request to the dApp and
              retrieves a report with all dragons.
            </p>

            <form>
              <label>
                <span>Dragon Id</span>
                <input type="number" onChange={(e) => setDragonId(Number(e.target.value))} />
              </label>
              {dragonId >= 0 ? <input type="submit" value="Dragon Status" onClick={checkDragon} /> : null}
              {dragonId >= 0 ? <input type="submit" value="Attack Dragon" onClick={attackDragon} /> : null}
            </form>
            <p>
              <strong>Attack:</strong> This is a write request that sends an input
              to the dApp, triggering the advance execution, which will generate
              notices.
            </p>
          </div>
          <div className='message'>
            <ReactJson theme={isDarkMode ? "monokai" : "bright:inverted"} displayDataTypes={false} src={message} style={{ color: 'rgb(253, 151, 31)' }} />
          </div>
        </> : null}
      </div>
    </>
  )
}

export default App
