// examples/tikua-front/src/App.tsx
import { useEffect, useState } from 'react'
import './App.css'
import Onboard, { WalletState } from '@web3-onboard/core'
import injectedModule from '@web3-onboard/injected-wallets'
import { Tikua, Address } from '@doiim/tikua'
import ReactJson from '@vahagn13/react-json-view'
import logo from './assets/logo.png'

// const playersList: Map<Address, number> = new Map()
// if (!playersList.has('0x0')) playersList.set('0x0', 100)
// playersList.set('0x0', Math.max(playersList.get('0x0')! - 30, 0))
// console.log(BigInt(playersList.get('0x0') || 0))

// Add property to allow JSON to be serialized on the frontend
// @ts-ignore
BigInt.prototype.toJSON = function () { return this.toString() }

// Web3Onboard module for injected wallets
const injected = injectedModule()

// Instantiating Web3Onboard
const onboard = Onboard({
  wallets: [injected],
  chains: [
    {
      id: '0x7A69',
      token: 'ETH',
      label: 'Local Sunodo',
      rpcUrl: 'http://localhost:8545'
    }
  ]
})

// Defining Dapp ABI
const abi = [
  "struct Dragon { uint256 id; uint256 life; }",
  "function attackDragon(uint256 dragonId)",
  "function drinkPotion()",
  "function heroStatus(address player) returns (uint256)",
  "function dragonStatus(uint256 dragonId) returns (uint256)",
  "function dragonsList() returns (Dragon[])",
];

function App() {

  const [wallets, setWallets] = useState<WalletState[]>([])
  const [dragonId, setDragonId] = useState<number>(0)
  const [message, setMessage] = useState<object>({})

  useEffect(() => {
    const state = onboard.state.select()
    const { unsubscribe } = state.subscribe((update) => {
      setWallets(update.wallets)
    })
    // return () => {
    //   unsubscribe()
    // }
  }, [])

  const connectWallet = async () => {
    setWallets(await onboard.connectWallet())
    startSubscription();
  }

  const attackDragon = async (e: any) => {
    e.preventDefault()
    const tikua = new Tikua({
      provider: onboard.state.get().wallets[0].provider,
      address: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
      account: wallets[0].accounts[0].address as Address,
      abi
    })
    await tikua.sendInput('attackDragon', [dragonId])
  }

  const drinkPotion = async () => {
    const tikua = new Tikua({
      provider: onboard.state.get().wallets[0].provider,
      address: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
      account: wallets[0].accounts[0].address as Address,
      abi
    })
    await tikua.sendInput('drinkPotion', [])
  }

  const checkLife = async () => {
    const tikua = new Tikua({
      provider: onboard.state.get().wallets[0].provider,
      endpoint: 'http://localhost:8080',
      abi
    })
    const status = await tikua.fetchInspect('heroStatus', [wallets[0].accounts[0].address as Address])
    setMessage({
      life: status
    })
  }

  const checkDragon = async (e: any) => {
    e.preventDefault()
    const tikua = new Tikua({
      provider: onboard.state.get().wallets[0].provider,
      endpoint: 'http://localhost:8080',
      address: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
      abi: abi
    })
    const status = await tikua.fetchInspect('dragonStatus', [dragonId])
    setMessage({
      dragonId: dragonId,
      status: status
    });
  }

  const dragonsList = async (e: any) => {
    e.preventDefault()
    const tikua = new Tikua({
      provider: onboard.state.get().wallets[0].provider,
      endpoint: 'http://localhost:8080',
      address: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
      abi: abi
    })
    const status = await tikua.fetchInspect('dragonsList', []) as any[]
    setMessage(status);
  }

  /**
   * This function starts a subscription by creating a new CartesiSDK instance
   * and adding a notices listener that updates the message state.
   *
   * @return {Promise<void>} Returns a Promise that resolves when the notices listener is added.
   */
  const startSubscription = async () => {
    const tikua = new Tikua({
      provider: onboard.state.get().wallets[0].provider,
      endpoint: 'http://localhost:8080',
      abi: abi
    })
    return tikua.addMyNoticesListener(
      1000,
      onboard.state.get().wallets[0].accounts[0].address as Address,
      (e) => setMessage(e)
    )
  }

  return (
    <>
      <img src={logo} width={200} height={200}></img>
      <h1>Tikua</h1>
      <p>an isomorphic Cartesi SDK</p>
      <div className="card">
        {wallets.length == 0 ?
          <button onClick={connectWallet}>Connect Wallet</button>
          : <p>Wallet: <span className='orange'>{wallets[0].accounts[0].address}</span></p>}
        <p>
          After connect your wallet successfully. Fill the form above.
        </p>
        <div className='heroCommands'>
          {wallets.length > 0 ?
            <button onClick={drinkPotion}>Drink Potion</button> : null
          }
          {wallets.length > 0 ?
            <button onClick={checkLife}>Check Hero Status</button> : null
          }
          {wallets.length > 0 ?
            <button onClick={dragonsList}>List Dragons</button> : null
          }
        </div>
        <form>
          <label>
            <span>Dragon Id</span>
            <input type="number" onChange={(e) => setDragonId(Number(e.target.value))} />
          </label>
          {dragonId > 0 ? <input type="submit" value="Dragon Status" onClick={checkDragon} /> : null}
          {dragonId > 0 ? <input type="submit" value="Attack Dragon" onClick={attackDragon} /> : null}
        </form>

        <div className='message'>
          <ReactJson theme="monokai" displayDataTypes={false} src={message} style={{ color: 'rgb(253, 151, 31)' }} />
        </div>
      </div>
    </>
  )
}

export default App

// examples/tikua-front-vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Tikua, Address } from '@doiim/tikua'

import VueJsonPretty from 'vue-json-pretty'
import 'vue-json-pretty/lib/styles.css';

// Add property to allow JSON to be serialized on the frontend
// @ts-ignore
BigInt.prototype.toJSON = function () { return this.toString() }

const ABI = [
  "struct Dragon { uint256 id; uint256 life; }",
  "function attackDragon(uint256 dragonId)",
  "function drinkPotion()",
  "function heroStatus(address player) returns (uint256)",
  "function dragonStatus(uint256 dragonId) returns (uint256)",
  "function dragonsList() returns (Dragon[])",
];

const walletAddress = ref<Address>();
const provider = ref()
const dragonIdInput = ref('')
const message = ref<any>({})

const connect = async () => {
  if (!window.ethereum) throw Error('MetaMask not found')
  await window.ethereum.request({ method: 'wallet_addEthereumChain', params: [{ chainId: '0x7A69', chainName: "Local Anvil", nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 }, rpcUrls: ['http://localhost:8545'] }] });
  const [account] = await window.ethereum.request({ method: 'eth_requestAccounts' })
  if (!account) throw Error('MetaMask reject')
  walletAddress.value = account
  provider.value = window.ethereum
  await startSubscription()
}

const startSubscription = async () => {
  if (!provider.value || !walletAddress.value) throw Error('Wallet not connected')
  const tikua = new Tikua({
    provider: provider.value,
    endpoint: 'http://localhost:8080',
    abi: ABI
  })
  tikua.addMyNoticesListener(
    1000,
    walletAddress.value,
    (e) => message.value = e
  )
}

const drinkPotion = async () => {
  if (!walletAddress.value) return
  const tikua = new Tikua({
    provider: provider.value,
    address: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
    account: walletAddress.value,
    abi: ABI
  })
  await tikua.sendInput('drinkPotion', [])
}

const checkLife = async () => {
  if (!walletAddress.value) return
  const tikua = new Tikua({
    provider: provider.value,
    endpoint: 'http://localhost:8080',
    abi: ABI
  })
  const status = await tikua.fetchInspect('heroStatus', [walletAddress.value])
  message.value = {
    life: status
  }
}

const dragonsList = async () => {
  const tikua = new Tikua({
    provider: provider.value,
    endpoint: 'http://localhost:8080',
    address: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
    abi: ABI
  })
  const status = await tikua.fetchInspect('dragonsList', []) as any[]
  message.value = status
}

const checkDragon = async () => {
  if (!dragonIdInput.value) return
  const tikua = new Tikua({
    provider: provider.value,
    endpoint: 'http://localhost:8080',
    address: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
    abi: ABI
  })
  const status = await tikua.fetchInspect('dragonStatus', [dragonIdInput.value])
  message.value = {
    drago: dragonIdInput.value,
    status: status
  }
}

const attackDragon = async () => {
  if (!dragonIdInput.value) return
  const tikua = new Tikua({
    provider: provider.value,
    address: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
    account: walletAddress.value,
    abi: ABI
  })
  await tikua.sendInput('attackDragon', [dragonIdInput.value])
}

</script>

<template>
  <div class="mx-auto my-auto flex flex-col justify-center items-center w-1/2 text-stone-600">
    <img src="./assets/logo.png" width=200 height=200 />
    <div class="text-center">
      <h1 class="text-5xl font-semibold">Tikua</h1>
      <p>an isomorphic Cartesi SDK</p>
    </div>


    <div class="my-10">
      <button v-if="!walletAddress" @click="connect"
        class="bg-stone-100 rounded-lg p-2 px-4 font-semibold text-lg hover:outline hover:outline-1 hover:outline-blue-600">Connect
        Wallet</button>
      <p v-else>Wallet: <span class="text-orange-400">{{ walletAddress }}</span></p>
    </div>

    <p class="my-2">
      After connect your wallet successfully. Fill the form above.
    </p>

    <div class="bg-stone-50 rounded-lg p-4 flex flex-col gap-2 border border-stone-100 w-[600px] my-2">
      <h1 class="uppercase text-sm font-semibold text-stone-500">Hero</h1>
      <div class="flex gap-4">
        <button :disabled="!walletAddress" @click="checkLife"
          class="bg-stone-100 rounded-lg p-2 px-4  text-md hover:outline hover:outline-1 hover:outline-blue-600">Check
          Health</button>
        <button :disabled="!walletAddress" @click="drinkPotion"
          class="bg-stone-100 rounded-lg p-2 px-4  text-md hover:outline hover:outline-1 hover:outline-blue-600">Drink
          Potion</button>
      </div>
    </div>


    <form class="bg-stone-50 rounded-lg p-4 flex flex-col gap-2 border border-stone-100 w-[600px] my-2">
      <h1 class="uppercase text-sm font-semibold text-stone-500">Dragon</h1>
      <div class="flex gap-4">
        <button @click.prevent="dragonsList"
          class="bg-stone-100 rounded-lg p-2 px-4  text-md hover:outline hover:outline-1 hover:outline-blue-600">List
          All Dragons</button>
        <input v-model="dragonIdInput" placeholder="Enter a dragon ID"
          class="bg-white rounded-lg p-2 px-4  text-md focus:outline focus:outline-1 focus:outline-blue-600 w-40" />

        <button @click.prevent="checkDragon" v-if="dragonIdInput"
          class="bg-stone-100 rounded-lg p-2 px-4  text-md hover:outline hover:outline-1 hover:outline-blue-600">Check
          Health</button>
        <button @click.prevent="attackDragon" :disabled="!walletAddress" v-if="dragonIdInput"
          class="bg-stone-100 rounded-lg p-2 px-4  text-md hover:outline hover:outline-1 hover:outline-blue-600">Attack</button>

      </div>
    </form>

    <div class="self-start my-2">
      <VueJsonPretty :data="message" :show-icon="true" theme="dark" />
    </div>

  </div>
</template>
